name: Run Automation Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=16.0.0'
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chrome Driver
        run: |
          LATEST_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -o chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          echo "CHROME_DRIVER_PATH=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests with Selenium
        run: |
          echo "webdriver.chrome.driver=$CHROME_DRIVER_PATH" >> $GITHUB_ENV
          mvn test
