name: Run Automation Tests

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install Chrome
        run: |
          CHROME_VERSION="113.0.5672.63"
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
          sudo dpkg -i google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
          sudo apt-get -f install -y

      - name: Install ChromeDriver
        run: |
          CHROME_DRIVER_VERSION="113.0.5672.63"
          wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up Chrome WebDriver
        run: echo "CHROME_DRIVER_PATH=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install -D skipTests

      - name: Display Chrome version
        run: google-chrome-stable --version

      - name: Display ChromeDriver version
        run: chromedriver --version

      - name: Set permissions for ChromeDriver
        run: sudo chmod +x /usr/local/bin/chromedriver

      - name: Set permissions for Chrome
        run: sudo chmod +x /usr/bin/google-chrome-stable

      - name: Run tests with Selenium
        run: |
          echo "webdriver.chrome.driver=$CHROME_DRIVER_PATH" >> $GITHUB_ENV
          mvn test
